sudo: required
services:
  - docker

before_install:
  - docker build  -t sawandevrani/frontend -f Dockerfile.dev .

script:
  - docker run sawandevrani/frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-west-2-525578825490"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_Access_key
  secret_access_key:
    secure: "$AWS_Secret_key"



  Frontend-env.bbr2ap4mp9.us-west-2.elasticbeanstalk.com